"""Embeds the chapter's full script into the website pages.

The style of the course wants every page to be readable on its own: besides the
link to the file on GitHub, the page contains the whole script inside a
collapsible block. Copying it by hand means letting it drift; here it is
regenerated.

How it works: every page declaring `**Script:** `python/NAME.py`` gets, at the
bottom, a block delimited by two HTML markers. What lies between the markers is
regenerated by this script; the rest of the page is untouched.

Usage:  python3 embed_code.py           # regenerate the blocks
        python3 embed_code.py --check   # check that they are up to date
"""
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DIR_SCRIPT = BASE / "python"
DIR_DOCS = BASE / "docs"

INIZIO = "<!-- embedded-script: begin (regenerated by python/embed_code.py) -->"
FINE = "<!-- embedded-script: end -->"
INTESTAZIONE = re.compile(r"\*\*Script:\*\*\s*`python/([A-Za-z0-9_]+)\.py`")


def blocco(nome: str) -> str:
    """The collapsible block with the whole script."""
    codice = (DIR_SCRIPT / f"{nome}.py").read_text().rstrip("\n")
    righe = codice.count("\n") + 1
    return "\n".join([
        INIZIO,
        "",
        f'??? example "Show the complete script — `python/{nome}.py` ({righe} lines)"',
        "",
        "    ```python",
        *[f"    {r}" if r else "" for r in codice.splitlines()],
        "    ```",
        "",
        FINE,
    ])


def pagina_principale(nome: str) -> str | None:
    """The page that "owns" the script: the one quoting it most often.

    The subpages of a chapter (for instance the fourteen techniques of chapter 3)
    quote the same script in their header: the whole script is embedded once
    only, on the main page.
    """
    candidate = []
    for pagina in sorted(DIR_DOCS.glob("*.md")):
        testo = pagina.read_text()
        quante = testo.replace(INIZIO, "").split(FINE)[0].count(f"python/{nome}.py") \
            if INIZIO in testo else testo.count(f"python/{nome}.py")
        if quante:
            candidate.append((-quante, len(pagina.stem), pagina.stem))
    return min(candidate)[2] if candidate else None


def aggiorna(pagina: Path) -> str | None:
    """The page text with the block updated, or None if it must not be touched."""
    testo = pagina.read_text()
    m = INTESTAZIONE.search(testo)
    if not m or not (DIR_SCRIPT / f"{m.group(1)}.py").exists():
        return None
    if pagina_principale(m.group(1)) != pagina.stem:
        if INIZIO not in testo:                       # subpage: nothing to do
            return None
        prima, resto = testo.split(INIZIO, 1)         # block to remove
        return (prima.rstrip("\n") + "\n" + resto.split(FINE, 1)[1].lstrip("\n"))
    nuovo = blocco(m.group(1))
    if INIZIO in testo:
        prima, resto = testo.split(INIZIO, 1)
        dopo = resto.split(FINE, 1)[1]
        return prima + nuovo + dopo
    return testo.rstrip("\n") + "\n\n" + nuovo + "\n"


def main() -> int:
    verifica = "--check" in sys.argv
    disallineate = []
    for pagina in sorted(DIR_DOCS.glob("*.md")):
        atteso = aggiorna(pagina)
        if atteso is None:
            continue
        if verifica:
            if pagina.read_text() != atteso:
                disallineate.append(pagina.name)
        elif pagina.read_text() != atteso:
            pagina.write_text(atteso)
            print(f"  [pagina] docs/{pagina.name}")
    if verifica:
        if disallineate:
            print("Pages with an out-of-date embedded script: "
                  + ", ".join(disallineate))
            print("Regenerate them with: python3 python/embed_code.py")
            return 1
        print("Every page has its embedded script up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
