"""Collection of the statements only: the problem texts, with no solution.

Serve per esercitarsi: gli stessi problemi della dispensa, nell'ordine dei
capitoli, ma senza modelli, bound e discussione. Si genera dai sorgenti della
dispensa --- non si scrive a mano --- cosi' resta allineato a ogni correzione.

Use:  python3 generate_collection.py          # writes notes/collection.tex
      python3 generate_collection.py --check   # checks that it is up to date
"""
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DIR_CAPITOLI = BASE / "notes" / "capitoli"
USCITA = BASE / "notes" / "collection.tex"

# l'ordine dei capitoli e' quello di main.tex
ORDINE = [
    ("Modelling", ["cap01_mip_models", "cap02_logic_binaries", "cap03_links",
                   "cap04_dual_bounds", "cap05_heuristics", "cap06_gurobi"]),
    ("The problems", ["cap00_numerical", "cap07_scheduling", "cap08_location",
                      "cap09_production", "cap10_mixed"]),
]

TITOLO_CAPITOLO = re.compile(r"\\chapter\*?\{([^}]*)\}")
PROBLEMA = re.compile(r"\\begin\{problema\}(\[[^\]]*\])?(.*?)\\end\{problema\}", re.S)


def sorgenti(nome: str):
    """Il file del capitolo piu' i suoi `\\input` (gli esercizi delle famiglie)."""
    principale = DIR_CAPITOLI / f"{nome}.tex"
    yield principale
    testo = principale.read_text(encoding="utf-8")
    for incluso in re.findall(r"\\input\{capitoli/([^}]+)\}", testo):
        percorso = DIR_CAPITOLI / f"{incluso.split('/', 1)[-1]}.tex" \
            if "/" not in incluso else DIR_CAPITOLI / f"{incluso}.tex"
        if percorso.exists():
            yield percorso


def enunciati(nome: str):
    """(titolo, corpo) di ogni `problema` del capitolo, nell'ordine del testo."""
    for percorso in sorgenti(nome):
        testo = percorso.read_text(encoding="utf-8")
        for m in PROBLEMA.finditer(testo):
            titolo = (m.group(1) or "[]")[1:-1]
            yield titolo, m.group(2).strip()


def titolo_capitolo(nome: str) -> str:
    testo = (DIR_CAPITOLI / f"{nome}.tex").read_text(encoding="utf-8")
    m = TITOLO_CAPITOLO.search(testo)
    return m.group(1) if m else nome


def documento() -> str:
    righe = [
        "% Generated by python/generate_collection.py --- do not edit by hand.",
        "\\documentclass[11pt,a4paper,oneside]{book}",
        "\\input{preambolo}",
        "\\title{MIP Modelling --- collection of statements}",
        "\\author{Fabio Furini}",
        "\\begin{document}",
        "\\begin{titlepage}",
        "  \\centering",
        "  \\vspace*{1.2cm}",
        "  \\href{https://www.diag.uniroma1.it/}{%",
        "    \\includegraphics[width=0.40\\textwidth]{figure/sapienza.jpeg}}\\\\[1.0cm]",
        "  {\\color{blunotte}\\rule{\\textwidth}{2pt}}\\\\[1.0cm]",
        "  {\\Huge\\bfseries\\color{blunotte} Collection of statements\\par}",
        "  \\vspace{0.7cm}",
        "  {\\Large\\color{teal} MIP Modelling --- the problems of the course,\\\\"
        "with no solution\\par}",
        "  \\vspace{0.7cm}",
        "  {\\color{blunotte}\\rule{\\textwidth}{2pt}}\\\\[1.2cm]",
        "  \\begin{tcolorbox}[colback=tealchiaro,colframe=teal,width=0.86\\textwidth,arc=2mm]",
        "    \\small The same problems as the notes, in the same order, with the texts",
        "    only: to practise before reading the solution. For each of them you are asked",
        "    for the model, the model of the instance, a constructive heuristic with its",
        "    bound, and the dual of the LP relaxation with a feasible dual solution.",
        "  \\end{tcolorbox}",
        "  \\vfill",
        "  {\\Large\\bfseries Fabio Furini\\par}",
        "  \\vspace{0.3cm}",
        "  {\\small Sapienza University of Rome --- A.Y. 2026--2027\\par}",
        "\\end{titlepage}",
        "\\tableofcontents",
    ]
    quanti = 0
    for parte, capitoli in ORDINE:
        contenuto = [(c, list(enunciati(c))) for c in capitoli]
        contenuto = [(c, e) for c, e in contenuto if e]
        if not contenuto:
            continue
        righe.append(f"\\part{{{parte}}}")
        for capitolo, blocchi in contenuto:
            righe.append(f"\\chapter{{{titolo_capitolo(capitolo)}}}")
            for titolo, corpo in blocchi:
                quanti += 1
                apri = f"\\begin{{problema}}[{titolo}]" if titolo else "\\begin{problema}"
                righe += [apri, corpo, "\\end{problema}", ""]
    righe.append("\\end{document}")
    righe.insert(1, f"% {quanti} statements")
    return "\n".join(righe) + "\n"


def main(verifica: bool = False) -> int:
    nuovo = documento()
    vecchio = USCITA.read_text(encoding="utf-8") if USCITA.exists() else ""
    if verifica:
        if nuovo != vecchio:
            print("notes/collection.tex is out of date: run generate_collection.py again")
            return 1
        print("Collection of statements up to date.")
        return 0
    USCITA.write_text(nuovo, encoding="utf-8")
    print(f"Written {USCITA.relative_to(BASE)} "
          f"({nuovo.count(chr(92) + 'begin{problema}')} statements)")
    return 0


if __name__ == "__main__":
    sys.exit(main(verifica="--check" in sys.argv))
